export const categories = [
  { label: 'Banco', value: 'bank' },
  { label: 'Bar', value: 'bar' },
  { label: 'Cafetería', value: 'cafeteria' },
  { label: 'Carpintería', value: 'carpentry' },
  { label: 'Centro comercial', value: 'shopping_center' },
  { label: 'Cocktails', value: 'cocktails' },
  { label: 'Comida rápida', value: 'fast_food' },
  { label: 'Fábrica', value: 'factory' },
  { label: 'Farmacia', value: 'pharmacy' },
  { label: 'Ferretería', value: 'hardware_store' },
  { label: 'Financiamiento', value: 'financing' },
  { label: 'Fotografía', value: 'photography' },
  { label: 'Gasolinería', value: 'gas_station' },
  { label: 'Heladería', value: 'ice_cream_shop' },
  { label: 'Iglesia', value: 'church' },
  { label: 'Jardinería', value: 'gardening' },
  { label: 'Joyería', value: 'jewelry_store' },
  { label: 'Librería', value: 'bookstore' },
  { label: 'Logística', value: 'logistics' },
  { label: 'Marroquinería', value: 'leather_goods' },
  { label: 'Mascotas', value: 'pets' },
  { label: 'Mercado', value: 'market' },
  { label: 'Música', value: 'music' },
  { label: 'Odontología', value: 'dentistry' },
  { label: 'Oficina', value: 'office' },
  { label: 'Parque de diversiones', value: 'amusement_park' },
  { label: 'Películas', value: 'movies' },
  { label: 'Piñatería', value: 'party_supplies' },
  { label: 'Pizzería', value: 'pizzeria' },
  { label: 'Restaurante', value: 'restaurant' },
  { label: 'Alquiler de ropa', value: 'clothing_rental' },
  { label: 'Tienda de ropa', value: 'clothing' },
  { label: 'Sex Shop', value: 'sex_shop' },
  { label: 'Technología', value: 'technology' },
  { label: 'Tienda para bebés', value: 'baby_store' },
  { label: 'Relojería', value: 'timer' },
  { label: 'Veterinaria', value: 'veterinary' },
  { label: 'Video Juegos', value: 'video_games' },
  { label: 'Zapatería', value: 'shoe_store' },
  { label: 'Otro', value: 'other' },
];
